### PR TITLE
A bunch of options, including --rtsopts and --high-core-rtsopts

### PR DESCRIPTION
**Pull request by deepfire**
This implements:

1. `--high-core-rtsopts` that passes `+RTS -A32M -q8n -RTS` to ghc
1. `--rtsopts OPTS` for custom options
1. `--attr NAME` (and the `ghc` attribute to time GHC builds), can be specified multiple times
1. `--profile NR` to pick profile from the JSON profile list, can be specified multiple times
1. Last, but not least: `--help`

### CODE REVIEW

**Comment by deepfire** [comment]
сс @christiaanb

**Comment by deepfire** [comment]
cc @christiaanb

**Comment by christiaanb** [comment]
Awesome, thanks!

**Comment by christiaanb** [comment]
Did it make any difference for your 3950X?

**Comment by deepfire** [comment]
@christiaanb, I wish I had one : -)

All benchmark results I cited (except for the 3770) came from openbenchmarking.org.

**Comment by christiaanb** [comment]
I'll try it on our `2990wx` once I'm back in the office.

**Comment by deepfire** [comment]
@christiaanb, I'd be interested in the results with the default RTS options as well, if I may ask! : -)

By the way, the default RTS options in the Nixpkgs' Haskell package builder is `-A64M`: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/generic-builder.nix#L180

**Pull request merged**
